[server]
headless = true
enableCORS = false
enableXsrfProtection = true
runOnSave = false

[browser]
gatherUsageStats = false

[theme]
base = "dark"
primaryColor = "#22c55e"
backgroundColor = "#000000"
secondaryBackgroundColor = "#0a0a0a"
textColor = "#ffffff"
